// <auto-generated />
namespace statsmachine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Warmachinedatamodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Warmachinedatamodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201701170528234_Warmachine-data-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
