// <auto-generated />
namespace statsmachine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class warmachine_model_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(warmachine_model_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020621406_warmachine_model_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
