// <auto-generated />
namespace statsmachine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class warmachineplayertoUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(warmachineplayertoUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020535278_warmachine-player-to-UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
