// <auto-generated />
namespace statsmachine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class warmachinemodelchanges01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(warmachinemodelchanges01));
        
        string IMigrationMetadata.Id
        {
            get { return "201701180654057_warmachine-model-changes-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
